# Generated by Django 5.0.5 on 2024-05-08 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Kopontren', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kasir',
            old_name='content',
            new_name='harga',
        ),
    ]
